[global]
log_level = "info"

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false

[rest]
enabled = false
host = "0.0.0.0"
port = 3000

[telemetry]
enabled = false
host = "0.0.0.0"
port = 3001

[[chains]]
id = "xrplevm_1450001-1"
type = "CosmosSdk"
rpc_addr = "http://172.30.0.10:26657"
grpc_addr = "http://172.30.0.10:9090"
event_source = { mode = "push", url = "ws://172.30.0.10:26657/websocket", batch_delay = "500ms" }
rpc_timeout = "10s"
trusted_node = true
account_prefix = "ethm"
key_name = "relayer-a"
key_store_folder = "/home/hermes/.hermes/keys"
address_type = { derivation = "ethermint", proto_type = { pk_type = "/ethermint.crypto.v1.ethsecp256k1.PubKey" } }
store_prefix = "ibc"
default_gas = 100000
max_gas = 4000000
gas_price = { price = 1, denom = "axrp" }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = "5s"
max_block_time = "30s"
trusting_period = "43200s"
trust_threshold = "2/3"

[chains.packet_filter]
policy = "allow"
list = [
  ["transfer", "*"],
]

[[chains]]
id = "xrplevm_1450002-1"
type = "CosmosSdk"
rpc_addr = "http://172.30.0.11:26657"
grpc_addr = "http://172.30.0.11:9090"
event_source = { mode = "push", url = "ws://172.30.0.11:26657/websocket", batch_delay = "500ms" }
rpc_timeout = "10s"
trusted_node = true
account_prefix = "ethm"
key_name = "relayer-b"
key_store_folder = "/home/hermes/.hermes/keys"
address_type = { derivation = "ethermint", proto_type = { pk_type = "/ethermint.crypto.v1.ethsecp256k1.PubKey" } }
store_prefix = "ibc"
default_gas = 100000
max_gas = 4000000
gas_price = { price = 1, denom = "axrp" }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = "5s"
max_block_time = "30s"
trusting_period = "43200s"
trust_threshold = "2/3"

[chains.packet_filter]
policy = "allow"
list = [
  ["transfer", "*"],
]

[[chains]]
id = "xrplevm_1450003-1"
type = "CosmosSdk"
rpc_addr = "http://172.30.0.12:26657"
grpc_addr = "http://172.30.0.12:9090"
event_source = { mode = "push", url = "ws://172.30.0.12:26657/websocket", batch_delay = "500ms" }
rpc_timeout = "10s"
trusted_node = true
account_prefix = "ethm"
key_name = "relayer-c"
key_store_folder = "/home/hermes/.hermes/keys"
address_type = { derivation = "ethermint", proto_type = { pk_type = "/ethermint.crypto.v1.ethsecp256k1.PubKey" } }
store_prefix = "ibc"
default_gas = 100000
max_gas = 4000000
gas_price = { price = 1, denom = "axrp" }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = "5s"
max_block_time = "30s"
trusting_period = "43200s"
trust_threshold = "2/3"

[chains.packet_filter]
policy = "allow"
list = [
  ["transfer", "*"],
]

